# Generated by Django 3.2.9 on 2021-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='decription'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(default='snack', max_length=64),
        ),
    ]
