# Generated by Django 3.2.9 on 2021-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20211116_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
